spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tian_test
    username: root
    password: ldap4$
    driverClassName: com.mysql.jdbc.Driver
    ## initialSize:初始化时建立物理连接的个数。，minIdle:最小连接池数量，maxActive:最大连接池数量
    initialSize: 2
    minIdle: 5
    maxActive: 20
    ## maxWait:配置获取连接等待超时的时间
    maxWait: 60000
    ## 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    ## 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    ## 验证连接有效与否的SQL，不同的数据配置不同
    ##  Oracle配置 spring.datasource.validationQuery=SELECT 1 FROM DUAL，
    ## 如果不配validationQuery项，则下面三项配置testWhileIdle，testOnBorrow， testOnReturn无用
    validationQuery: SELECT 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    ## 打开PSCache，并且指定每个连接上PSCache的大小。PSCache对支持游标的数据库性能提升巨大，比如说oracle。
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    maxOpenPreparedStatements: 20
    ##  属性类型是字符串，通过别名的方式配置扩展插件，
    ##  常用的插件有：监控统计用的filter:stat 日志用的filter:log4j 防御sql注入的filter:wall
    filters: stat
#    # 访问的用户名
#    loginUsername: tps
#    # 访问的密码
#    loginPassword: tps
# ====================MybatisPlus====================
#mybatisPlus:
#  globalConfig:
#    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
#    idType: 0
#    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
#    fieldStrategy: 2
#    #驼峰下划线转换
#    dbColumnUnderline: true
#    #刷新mapper 调试神器
#    isRefresh: true
#    #数据库大写下划线转换
#    isCapitalMode: true
#    #逻辑删除配置
#    logicDeleteValue: 0
#    logicNotDeleteValue: 1
###########################  druid配置   ##########################
#spring.datasource.type=com.alibaba.druid.pool.DruidDataSource#
## 通过connectProperties属性来打开mergeSql功能；慢SQL记录
#spring.datasource.connectionProperties=druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
## 合并多个DruidDataSource的监控数据
#spring.datasource.useGlobalDataSourceStat=true
#
#
# mybatis_config
# mybatis:
#   mapper-locations: classpath:mapper/*Mapper.mapper
#   typeAliasesPackage: tian.pusen.mybatisplusplus.entity
