spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tian_test
    username: root
    password: ldap4$
    driverClassName: com.mysql.jdbc.Driver

# mybatis_config
mybatis:
  mapper-locations: classpath:mapper/*Mapper.mapper
  typeAliasesPackage: tian.pusen.mybatis.entity
