spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tian_test
    username: root
    password: ldap4$
    driverClassName: com.mysql.jdbc.Driver
    ## initialSize:初始化时建立物理连接的个数。，minIdle:最小连接池数量，maxActive:最大连接池数量
    initialSize: 2
    minIdle: 5
    maxActive: 20
    ## maxWait:配置获取连接等待超时的时间
    maxWait: 60000
    ## 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    ## 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    ## 验证连接有效与否的SQL，不同的数据配置不同
    ##  Oracle配置 spring.datasource.validationQuery=SELECT 1 FROM DUAL，
    ## 如果不配validationQuery项，则下面三项配置testWhileIdle，testOnBorrow， testOnReturn无用
    validationQuery: SELECT 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    ## 打开PSCache，并且指定每个连接上PSCache的大小。PSCache对支持游标的数据库性能提升巨大，比如说oracle。
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    maxOpenPreparedStatements: 20
    ##  属性类型是字符串，通过别名的方式配置扩展插件，
    ##  常用的插件有：监控统计用的filter:stat 日志用的filter:log4j 防御sql注入的filter:wall
    filters: stat

